Add missing release requirement
Before this change, we saw an error in CI when we tried to make a
release:

    ModuleNotFoundError: No module named 'packaging'